"""empty message

Revision ID: 2255ef01f035
Revises: e1c51cf03a79
Create Date: 2026-05-22 20:48:59.338914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2255ef01f035'
down_revision: Union[str, Sequence[str], None] = 'e1c51cf03a79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('win_count', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('lose_count', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('draw_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'draw_count')
    op.drop_column('users', 'lose_count')
    op.drop_column('users', 'win_count')
    # ### end Alembic commands ###
